- name: Install virtualenv packages
  apt:
    name: [ python3-venv ]
    state: latest

- name: Creates directory
  file:
    path: "{{ autoscaling_home }}"
    state: directory
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }}  already installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed

 - name: Install requirements
   become_user: "{{ autoscaling_user }}"       
   pip: 
        requirements: /vagrant/configs/requirements.txt
        virtualenv: "{{ autoscaling_home }}/{{ autoscaling_env }}"
        virtualenv_python: python3.9
        
- name: Install pip packages
  pip:
    name: [cython,requests,pyyaml,pandas,numpy,matplotlib]
    virtualenv: "{{ autoscaling_home }}/{{ autoscaling_env }}"
    state: latest
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }} installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed

#- name: Source autoscaling python environment
#  ansible.builtin.lineinfile:
#    path=/home/{{autoscaling_user}}/.bashrc
#    line="source '{{ autoscaling_home }}/{{ autoscaling_env }}/bin/activate'"
#    regexp="^source '{{ autoscaling_home }}/{{ autoscaling_env }}/bin/activate'"
#    state=present
#    insertafter=EOF
#  become_user: "{{ autoscaling_user }}"
#  when: virtualenv_installed.stat.exists == True
