- name: Check if pyslurm already installed
  shell: "{{ autoscaling_home }}/{{autoscaling_env}}/bin/python -m pip list | grep pyslurm"
  register: pyslurm_installed
  ignore_errors: true

- name: Git checkout pyslurm
  ansible.builtin.git:
    repo: 'https://github.com/PySlurm/pyslurm.git'
    dest: "{{ autoscaling_home }}/pyslurm"
    version: slurm-20.11.8
    force: yes
    update: yes
  become_user: "{{ autoscaling_user }}"
  when: pyslurm_installed is failed

- name: Change slurmfull to slurm
  ansible.builtin.shell: sed -i 's/slurmfull/slurm/' "{{ autoscaling_home }}/pyslurm/setup.py"
  args:
    executable: /bin/bash
  run_once: true
  become_user: "{{ autoscaling_user }}"
  when: pyslurm_installed is failed

- name: Pyslurm build
  ansible.builtin.shell: "cd {{ autoscaling_home }}/pyslurm && {{ autoscaling_home }}/{{autoscaling_env}}/bin/python setup.py build --slurm=/usr/ --slurm-inc=/usr/include/ --slurm-lib=/usr/lib/x86_64-linux-gnu/"
  args:
    executable: /bin/bash
  run_once: true
  become_user: "{{ autoscaling_user }}"
  when: pyslurm_installed is failed

- name: Pyslurm install
  ansible.builtin.shell: "cd {{ autoscaling_home }}/pyslurm && {{ autoscaling_home }}/{{autoscaling_env}}/bin/python setup.py install && {{ autoscaling_home }}/{{autoscaling_env}}/bin/python setup.py clean"
  args:
    executable: /bin/bash
  run_once: true
  become_user: "{{ autoscaling_user }}"
  when: pyslurm_installed is failed